import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NavPage } from "@/src/components/layout/nav";
import Footer from "@/src/components/layout/footer";
import { WishlistProvider } from "@/src/context/wishlist-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavPage />

        <main className="mt-24 min-h-screen overflow-x-hidden">
          <WishlistProvider>
            {children}
          </WishlistProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}