import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NavPage } from "@/src/components/layout/nav";
import Footer from "@/src/components/layout/footer";
import { WishlistProvider } from "@/src/context/wishlist-context";
import { cookies } from "next/headers";
import { fetchAPI } from "@/src/utils/apiService";
import CartSync from "@/src/features/cart/cartSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const cookieHeader = cookieStore.getAll().map((cookie) => `${cookie.name}=${cookie.value}`).join(";")


  const res = await fetchAPI({
    endPoint: "users/me",
    headers:{
      Cookie: cookieHeader,
    },
    revalidateSeconds: 0,
  })

  const profile = res?.data?.data ?? null;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavPage profile = {profile}  />

        <main className="mt-24 min-h-screen overflow-x-hidden">
          <WishlistProvider>
            {/* <CartSync isLoggedIn={!!profile}>

            </CartSync> */}
            {children}
          </WishlistProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}